version: '3.8'

services:

  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./symfony:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db
      - node

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./symfony:/var/www/html:delegated
    ports:
      - '3000:9000'

  db:
    image: 'postgres:15.5-alpine3.18'
    env_file:
      - ./env/postgres.env

  node:
    image: 'node:21-alpine3.17'
    working_dir: /home/node/app
    ports:
      - '8001:8001'
    volumes:
      - ./vue:/home/node/app
    tty: true

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./symfony:/var/www/html

  symfony-console:
    build:
      context: ./dockerfiles
      dockerfile: symfony-console.dockerfile
    volumes:
      - ./symfony:/var/www/html
    entrypoint:
      - /bin/sh
      - -c
      - 'php bin/console "$@"'
#  npm:
